config/routes.rb
Rails.application.routes.draw do
  root 'weather#index'
  get 'weather', to: 'weather#fetch_forecast'
  get 'weather_per_day', to: 'weather#forecast_per_day'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController

  # root page
  def index
  end

  def fetch_forecast
    forecast = Communicator.new({
      city: weather_params[:q]
      }).fetch_daily_forecast
    render 'fetch_forecast', :locals =>{:data => forecast}
  end

  def forecast_per_day
    render 'forecast_per_day', :locals =>{:data => params}
  end

  private
    
    def weather_params
      params.permit(:q)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeatherApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js"></script>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/weather/fetch_forecast.html.erb
<% if data["message"] == "city not found" %>
  <div class="card-container col-md-12">
    <div class="detail-title">
        <%= link_to "<--- Go Back", root_path %> <b>Please go back and enter a real city's name </b>
    </div>
  </div>

<% else %>
  <div class="card-container col-md-12">
  <%= link_to "<--- Go Back", root_path %> 
    <div class="detail-title">
      <i><%= data['city']['name'] %></i> Weather Forecast
    </div>
  <div class="card-group">
    <% data['list'].each do |day| %>
      <div class="card col-md-3 card-design">
          <div class="card-block">
            <h4 class="card-title"><%= Time.at(day['dt']).strftime('%e %b %Y ') %></h4>
            <p class="card-text"><b>Min:</b> <%=day['temp']['min']  %></p>
            <p class="card-text"><b>Max:</b> <%=day['temp']['max'] %></p>
            <p class="card-text"><small>Unit Default: Kelvin</small></p>
        </div>
        <div class="card-footer">
          <%= link_to "More Details+", weather_per_day_path(day), method: :get %>
        </div>
      </div>
    <% end %>
  </div>
  </div>
<% end %>

app/views/weather/forecast_per_day.html.erb
<div class="col-md-3">
  <div style="float: right;">
    <%= link_to "<--- Go Back", request.referer %>
  </div>
</div>
<div class="container col-md-6">
  <div class="detail-title">
    <i><%= DateTime.strptime(params['dt'],'%s').strftime('%e %b %Y ') %></i> Weather Forecast
  </div>
  <ul class="list-group" style="text-align: center;">
    <li class="list-group-item list-group-item-success"><b>Weather: </b><%= params['weather'][0]['description']%></li>
    <li class="list-group-item list-group-item-info"><b>Cloud cover: </b><%=params['clouds']%> %</li>
    <li class="list-group-item list-group-item-warning"><b>Humidity: </b><%=params['humidity']%> %</li>
    <li class="list-group-item list-group-item-info"><b>Wind Speed: </b><%=params['speed']%> meter/sec</li>
    <li class="list-group-item list-group-item-warning"><b>Wind Direction: </b><%=params['deg']%> degrees</li>
  </ul>
</div>
<div class="col-md-3">
</div>

app/views/weather/index.html.erb
<div class="col-md-4">
</div>
<div class="col-md-4">
  <div class="jumbotron">
    <%= form_tag("/weather", method: "get") do %>
      <%= label_tag(:q, "Enter city:") %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("fetch") %>
    <% end %>
  </div>
</div>
<div class="col-md-4">
</div>